# Generated by Django 4.0.4 on 2022-04-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_delete_profle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='othernames',
        ),
    ]
